// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svafesppcjumyfmpxzpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2YWZlc3BwY2p1bXlmbXB4enBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTc1MTMsImV4cCI6MjA3NDU3MzUxM30.22SKe7-D17iSMulY_UTGU0CLkYdDysAkiw4Nfhtd7ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});